name: Test Log Analyzer
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Get repo
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run tests
        run: puthon3 src/unittest_log_analyzer.py